import type { SkillsConfig } from "@/types/skills";

export const skillsConfig: SkillsConfig = {
  categories: [
    { id: "frontend", label: "Frontend", color: "from-blue-500 to-cyan-500" },
    { id: "backend", label: "Backend", color: "from-green-500 to-emerald-500" },
    { id: "languages", label: "Langages", color: "from-violet-500 to-purple-500" },
    { id: "database", label: "Base de données", color: "from-orange-500 to-amber-500" },
    { id: "tools", label: "Outils & DevOps", color: "from-pink-500 to-rose-500" },
    { id: "design", label: "Design", color: "from-yellow-500 to-amber-500" },
  ],
  table: {
    available: true,
    url: "/doc/skills-table-rubio-abela.pdf",
  },
  skills: [
    // Frontend
    {
      name: "HTML",
      category: "frontend",
      icon: "/icons/html.svg",
      startYear: 2022,
      level: 5,
      description: "Maîtrise complète du HTML5 et sémantique",
    },
    {
      name: "CSS",
      category: "frontend",
      icon: "/icons/css.svg",
      startYear: 2022,
      level: 4,
      description: "CSS3, Flexbox, Grid, Animations",
    },
    {
      name: "Tailwind CSS",
      category: "frontend",
      icon: "/icons/tailwind.svg",
      startYear: 2023,
      level: 4,
      description: "Utilitaires, Personnalisation, Responsive Design",
    },
    {
      name: "React",
      category: "frontend",
      icon: "/icons/react.svg",
      startYear: 2023,
      level: 4,
      description: "Hooks, Context, Components",
    },
    {
      name: "Astro",
      category: "frontend",
      icon: "/icons/astro.svg",
      startYear: 2024,
      level: 4,
      description: "SSG, Islands, Intégrations",
    },
    // Languages
    {
      name: "JavaScript",
      category: "languages",
      icon: "/icons/javascript.svg",
      startYear: 2022,
      level: 4,
      description: "ES6+, DOM, Async/Await",
    },
    {
      name: "TypeScript",
      category: "languages",
      icon: "/icons/typescript.svg",
      startYear: 2024,
      level: 3,
      description: "Types, Interfaces, Generics",
    },
    {
      name: "C#",
      category: "languages",
      icon: "/icons/csharp.svg",
      startYear: 2023,
      level: 3,
      description: "POO, LINQ, .NET",
    },
    {
      name: "Python",
      category: "languages",
      icon: "/icons/python.svg",
      startYear: 2021,
      endYear: 2023,
      level: 3,
      description: "Scripts",
    },
    {
      name: "C++",
      category: "languages",
      icon: "/icons/cpp.svg",
      startYear: 2021,
      endYear: 2023,
      level: 2,
      description: "POO, Algorithmes, Arduino",
    },
    {
      name: "Lua",
      category: "languages",
      icon: "/icons/lua.svg",
      startYear: 2022,
      endYear: 2023,
      level: 2,
      description: "Scripting, modding",
    },
    // Backend
    {
      name: "Node.js",
      category: "backend",
      icon: "/icons/nodejs.svg",
      startYear: 2024,
      level: 4,
      description: "Express, API REST",
    },
    // Database
    {
      name: "SQL",
      category: "database",
      icon: "/icons/sql.svg",
      startYear: 2024,
      level: 3,
      description: "MySQL, PostgreSQL, Requêtes avancées",
    },
    {
      name: "MongoDB",
      category: "database",
      icon: "/icons/mongodb.svg",
      startYear: 2024,
      level: 2,
      description: "NoSQL, Aggregation, Indexation",
    },
    // Tools
    {
      name: "Docker",
      category: "tools",
      icon: "/icons/docker.svg",
      startYear: 2025,
      level: 2,
      description: "Conteneurisation, Docker Compose",
    },
    {
      name: "WordPress",
      category: "tools",
      icon: "/icons/wordpress.svg",
      startYear: 2024,
      level: 3,
      description: "Thèmes, Plugins, Personnalisation",
    },
    // Design
    {
      name: "Figma",
      category: "design",
      icon: "/icons/figma.svg",
      startYear: 2022,
      level: 4,
      description: "UI/UX, Prototypage, Design System",
    },
  ],
};
